name: Linting and style checking

on: [push, pull_request]

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # TODO don't ignore octo-buffer.lua when the issue with stylua is fixed
          args:  stylua -g \!*octo-buffer.lua --color always --check lua/
